name: cinemind

services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: cinemind
      POSTGRES_PASSWORD: cinemind
      POSTGRES_DB: cinemind
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: